const baseUrl = 'http://localhost:8079/luke_blog'
module.exports={
    devServer:{
        proxy:{
            '/user':{
                target:baseUrl,
                changeOrigin:true
            },
            '/admin':{
                target:baseUrl,
                changeOrigin:true
            },
            '/portal':{
                target:baseUrl,
                changeOrigin:true
            }
        }
    }
};